# Generated by Django 5.1.6 on 2025-03-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('time', models.DateTimeField()),
                ('priority', models.CharField(choices=[('urgent-important', 'Urgent and Important'), ('important-not-urgent', 'Important, but Not Urgent'), ('urgent-not-important', 'Urgent, but Not Important'), ('neither', 'Neither Urgent nor Important')], default='neither', max_length=50)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
